name: fortune_wheel_demo
version: 1.0.0

publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  auto_route: ^2.2.0
  flutter_hooks: ^0.16.0
  flutter_fortune_wheel:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  auto_route_generator: 2.1.0
  build_runner: 2.0.2

flutter:
  uses-material-design: true
